// categories.js
import { MaterialIcons, FontAwesome, Ionicons, Entypo } from '@expo/vector-icons';

export const categories = [
  {
    name: 'ACCESSORIES',
    icon: 'flag',
    iconLibrary: 'MaterialIcons',
    upcomingAmount: 120,
  },
  {
    name: 'BABY',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 150,
  },
  {
    name: 'BAG',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 80,
  },
  {
    name: 'BOTH',
    icon: 'flag',
    iconLibrary: 'Ionicons',
    upcomingAmount: 100,
  },
  {
    name: 'BRACELET',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 45,
  },
  {
    name: 'CAP',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 60,
  },
  {
    name: 'CLASSIC',
    icon: 'classic-computer',
    iconLibrary: 'Entypo',
    upcomingAmount: 50,
  },
  {
    name: 'DRESSING',
    icon: 'flag',
    iconLibrary: 'Ionicons',
    upcomingAmount: 200,
  },
  {
    name: 'GENERAL',
    icon: 'female',
    iconLibrary: 'MaterialIcons',
    upcomingAmount: 300,
  },
  {
    name: 'HAT',
    icon: 'gavel',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 90,
  },
  {
    name: 'JACKET',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 110,
  },
  {
    name: 'LATEST',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 250,
  },
  {
    name: 'MAN',
    icon: 'male',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 130,
  },
  {
    name: 'MEN',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 140,
  },
  {
    name: 'PANT',
    icon: 'tint',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 75,
  },
  {
    name: 'PARFUM',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 50,
  },
  {
    name: 'flag',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 30,
  },
  {
    name: 'SHADES',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 70,
  },
  {
    name: 'flag',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 180,
  },
  {
    name: 'SHOES',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 200,
  },
  {
    name: 'SHORT',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 45,
  },
  {
    name: 'SHORTs',
    icon: 'flag',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 65,
  },
  {
    name: 'SUITs',
    icon: 'business-center',
    iconLibrary: 'MaterialIcons',
    upcomingAmount: 90,
  },
  {
    name: 'SWEATER',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 120,
  },
  {
    name: 'T-flag',
    icon: 'female',
    iconLibrary: 'MaterialIcons',
    upcomingAmount: 100,
  },
  {
    name: 'TROUSER',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 140,
  },
  {
    name: 'WATCH',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 200,
  },
  {
    name: 'WATCHES',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 250,
  },
  {
    name: 'female',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 160,
  },
  {
    name: 'WOMEN',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 180,
  },
  {
    name: 'DRESSES',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 220,
  },
  {
    name: 'COMPLETE',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 300,
  },
  {
    name: 'SKIRTS',
    icon: 'female',
    iconLibrary: 'FontAwesome',
    upcomingAmount: 130,
  },
  {
    name: 'TOPS',
    icon: 'female',
    iconLibrary: 'Ionicons',
    upcomingAmount: 90,
  },
];
